export const VEHICLE_BRANDS = [
  "Abarth",
  "Acura",
  "Alfa Romeo",
  "Alpine",
  "Ariel",
  "Aston Martin",
  "Audi",
  "BAC",
  "Bentley",
  "BMW",
  "Bugatti",
  "Buick",
  "BYD",
  "Cadillac",
  "Changan",
  "Chery",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Cupra",
  "Daihatsu",
  "De Tomaso",
  "Dodge",
  "Donkervoort",
  "DS Automobiles",
  "Ferrari",
  "Fiat",
  "Ford",
  "Genesis",
  "Geely",
  "GMC",
  "GWM",
  "Hennessey",
  "Honda",
  "Hongqi",
  "Hyundai",
  "Infiniti",
  "Isuzu",
  "Jaguar",
  "Jeep",
  "Kia",
  "Koenigsegg",
  "Lamborghini",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "Lucid",
  "Lynk & Co",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MG",
  "Mini",
  "Mitsubishi",
  "Morgan",
  "NIO",
  "Nissan",
  "Opel",
  "Pagani",
  "Peugeot",
  "Polestar",
  "Porsche",
  "Ram",
  "Renault",
  "Rimac",
  "Rivian",
  "Rolls-Royce",
  "SEAT",
  "Škoda",
  "Smart",
  "SSC",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
  "W Motors",
  "Xpeng",
  "Zeekr",
] as const

export type VehicleBrand = (typeof VEHICLE_BRANDS)[number]

export const MODELS_BY_BRAND: Record<VehicleBrand, readonly string[]> = {
  Abarth: ["595", "695", "Pulse Abarth"],

  Acura: ["Integra", "TLX", "RDX", "MDX", "ZDX"],

  "Alfa Romeo": [
    "Giulia",
    "Stelvio",
    "Tonale",
    "Junior",
    "4C",
    "8C Competizione",
    "Giulietta",
    "MiTo",
  ],

  Alpine: ["A110", "A290"],

  Ariel: ["Atom", "Nomad"],

  "Aston Martin": [
    "Vantage",
    "DB11",
    "DB12",
    "DBS Superleggera",
    "DBX",
    "Valkyrie",
    "Valhalla",
  ],

  Audi: [
    "A1",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "TT",
    "Q2",
    "Q3",
    "Q5",
    "Q7",
    "Q8",
    "R8",
    "RS3",
    "RS5",
    "RS6",
    "RS7",
    "RS Q8",
    "e-tron GT",
  ],

  BAC: ["Mono"],

  Bentley: ["Continental GT", "Flying Spur", "Bentayga"],

  BMW: [
    "Serie 1",
    "Serie 2",
    "Serie 3",
    "Serie 4",
    "Serie 5",
    "Serie 7",
    "Serie 8",
    "Z4",
    "M2",
    "M3",
    "M4",
    "M5",
    "M8",
    "XM",
    "X1",
    "X3",
    "X5",
    "X6",
    "X7",
    "i4",
    "i5",
    "i7",
    "iX",
  ],

  Bugatti: ["Veyron", "Chiron", "Divo", "Centodieci", "Bolide", "Tourbillon"],

  Buick: ["Enclave", "Encore", "Envision", "Envista"],

  BYD: [
    "Dolphin",
    "Seal",
    "Han",
    "Tang",
    "Atto 3",
    "Yuan Plus",
    "Song Plus",
    "Qin Plus",
    "Seagull",
    "Yangwang U8",
  ],

  Cadillac: [
    "Escalade",
    "Escalade IQ",
    "CT4",
    "CT5",
    "Lyriq",
    "Optiq",
    "Celestiq",
    "XT4",
    "XT5",
    "XT6",
  ],

  Changan: [
    "CS35 Plus",
    "CS55 Plus",
    "CS75 Plus",
    "UNI-T",
    "UNI-K",
    "Alsvin",
    "Deepal S7",
  ],

  Chery: ["Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8", "Omoda 5", "Jaecoo 7", "Arrizo 6"],

  Chevrolet: [
    "Corvette",
    "Camaro",
    "Malibu",
    "Impala",
    "Spark",
    "Onix",
    "Cruze",
    "Aveo",
    "Cavalier",
    "Tahoe",
    "Suburban",
    "Equinox",
    "Blazer",
    "Tracker",
    "Traverse",
    "Trailblazer",
    "Captiva",
    "Silverado",
    "Colorado",
    "S10",
    "Montana",
    "Bolt EV",
    "Blazer EV",
  ],

  Chrysler: ["300", "Pacifica", "Voyager", "PT Cruiser"],

  Citroën: [
    "C3",
    "C3 Aircross",
    "C4",
    "C4 Cactus",
    "C5 Aircross",
    "Berlingo",
    "Ami",
  ],

  Cupra: ["Formentor", "Born", "Leon", "Ateca", "Tavascan", "Terramar"],

  Daihatsu: ["Terios", "Rocky", "Copen", "Tanto"],

  "De Tomaso": ["Pantera", "Mangusta", "P72"],

  Dodge: [
    "Charger",
    "Challenger",
    "Viper",
    "Dart",
    "Neon",
    "Durango",
    "Hornet",
    "Journey",
    "Caravan",
  ],

  Donkervoort: ["D8 GTO", "F22"],

  "DS Automobiles": ["DS 3", "DS 4", "DS 7", "DS 9"],

  Ferrari: [
    "250 GTO",
    "Testarossa",
    "F40",
    "F50",
    "Enzo",
    "LaFerrari",
    "458 Italia",
    "488 GTB",
    "F8 Tributo",
    "SF90 Stradale",
    "812 Superfast",
    "Roma",
    "296 GTB",
    "Purosangue",
    "12Cilindri",
    "F80",
  ],

  Fiat: [
    "500",
    "Panda",
    "Uno",
    "Cronos",
    "Pulse",
    "Fastback",
    "Tipo",
    "Punto",
    "124 Spider",
    "Strada",
    "Toro",
    "Ducato",
    "Fiorino",
  ],

  Ford: [
    "Mustang",
    "Focus",
    "Fiesta",
    "Fusion",
    "GT",
    "Contour",
    "Explorer",
    "Escape",
    "Bronco",
    "Bronco Sport",
    "Edge",
    "Expedition",
    "EcoSport",
    "Puma",
    "F-150",
    "Ranger",
    "Maverick",
    "Super Duty",
    "Transit",
  ],

  Genesis: ["G70", "G80", "G90", "GV70", "GV80", "GV60"],

  Geely: ["Coolray", "Monjaro", "Tugella", "Geometry C", "Emgrand", "Okavango"],

  GMC: ["Sierra", "Canyon", "Yukon", "Acadia", "Terrain", "Hummer EV"],

  GWM: ["Haval H6", "Haval Jolion", "Tank 300", "Tank 500", "Poer", "Ora 03"],

  Hennessey: ["Venom GT", "Venom F5"],

  Honda: [
    "Civic",
    "Accord",
    "Fit",
    "Jazz",
    "City",
    "Prelude",
    "S2000",
    "NSX",
    "CR-V",
    "HR-V",
    "Pilot",
    "Passport",
    "ZR-V",
    "Prologue",
    "Ridgeline",
    "Odyssey",
  ],

  Hongqi: ["H5", "H9", "E-HS9"],

  Hyundai: [
    "Elantra",
    "Avante",
    "Accent",
    "Sonata",
    "Grand i10",
    "Ioniq 5",
    "Ioniq 6",
    "Tucson",
    "Santa Fe",
    "Kona",
    "Palisade",
    "Creta",
    "Venue",
    "Veloster",
    "Elantra N",
    "Kona N",
  ],

  Infiniti: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],

  Isuzu: ["D-Max", "MU-X", "Trooper"],

  Jaguar: ["XE", "XF", "XJ", "F-Pace", "E-Pace", "I-Pace", "F-Type"],

  Jeep: [
    "Wrangler",
    "Grand Cherokee",
    "Cherokee",
    "Compass",
    "Renegade",
    "Gladiator",
    "Wagoneer",
    "Grand Wagoneer",
    "Avenger",
  ],

  Kia: [
    "Picanto",
    "Rio",
    "Forte",
    "K3",
    "K5",
    "Optima",
    "Stinger",
    "EV6",
    "EV9",
    "Sportage",
    "Sorento",
    "Telluride",
    "Seltos",
    "Soul",
    "Sonet",
    "Carnival",
  ],

  Koenigsegg: ["CC8S", "CCX", "Agera", "Regera", "Jesko", "Gemera"],

  Lamborghini: [
    "Miura",
    "Countach",
    "Diablo",
    "Murciélago",
    "Gallardo",
    "Aventador",
    "Huracán",
    "Revuelto",
    "Temerario",
    "Urus",
  ],

  Lancia: ["Ypsilon", "Delta", "Delta HF Integrale", "Stratos"],

  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Range Rover",
    "Range Rover Sport",
    "Range Rover Velar",
    "Range Rover Evoque",
  ],

  Lexus: ["IS", "ES", "LS", "NX", "RX", "GX", "LX", "LC", "LFA", "RZ"],

  Lincoln: ["Navigator", "Aviator", "Nautilus", "Corsair"],

  Lotus: ["Elise", "Exige", "Evora", "Emira", "Eletre", "Evija", "Emeya"],

  Lucid: ["Air", "Gravity"],

  "Lynk & Co": ["01", "02", "03", "05", "08", "09"],

  Maserati: [
    "GranTurismo",
    "GranCabrio",
    "Ghibli",
    "Quattroporte",
    "MC20",
    "Levante",
    "Grecale",
  ],

  Mazda: [
    "Mazda2",
    "Mazda3",
    "Mazda6",
    "MX-5 Miata",
    "RX-7",
    "RX-8",
    "CX-30",
    "CX-5",
    "CX-50",
    "CX-60",
    "CX-70",
    "CX-90",
    "MX-30",
  ],

  McLaren: [
    "570S",
    "720S",
    "750S",
    "765LT",
    "Artura",
    "Senna",
    "P1",
    "Speedtail",
    "GTS",
  ],

  "Mercedes-Benz": [
    "Clase A",
    "Clase C",
    "Clase E",
    "Clase S",
    "CLA",
    "CLS",
    "GLA",
    "GLC",
    "GLE",
    "GLS",
    "Clase G",
    "AMG GT",
    "SL Roadster",
    "EQE",
    "EQS",
  ],

  MG: ["MG3", "MG5", "MG GT", "ZS", "HS", "MG4 EV", "Cyberster"],

  Mini: ["Cooper 3p", "Cooper 5p", "Convertible", "Clubman", "Countryman"],

  Mitsubishi: [
    "Lancer",
    "Lancer Evolution",
    "Outlander",
    "Eclipse Cross",
    "Montero",
    "Pajero",
    "ASX",
    "Triton",
    "L200",
    "Mirage",
  ],

  Morgan: ["Plus Four", "Plus Six", "Super 3"],

  NIO: ["ET5", "ET7", "ES6", "ES8", "EC6", "EP9"],

  Nissan: [
    "GT-R",
    "350Z",
    "370Z",
    "Z",
    "Z Nismo",
    "Sentra",
    "Altima",
    "Maxima",
    "Versa",
    "March",
    "Micra",
    "Kicks",
    "X-Trail",
    "Rogue",
    "Pathfinder",
    "Murano",
    "Armada",
    "Patrol",
    "Frontier",
    "Navara",
    "Titan",
    "Leaf",
    "Ariya",
  ],

  Opel: ["Corsa", "Astra", "Insignia", "Mokka", "Grandland"],

  Pagani: ["Zonda", "Huayra", "Utopia"],

  Peugeot: [
    "208",
    "308",
    "408",
    "508",
    "2008",
    "3008",
    "5008",
    "Partner",
    "Rifter",
  ],

  Polestar: ["Polestar 1", "Polestar 2", "Polestar 3", "Polestar 4"],

  Porsche: [
    "911",
    "718 Cayman",
    "718 Boxster",
    "918 Spyder",
    "Carrera GT",
    "Cayenne",
    "Macan",
    "Panamera",
    "Taycan",
  ],

  Ram: ["1500", "2500", "3500", "ProMaster", "Rampage"],

  Renault: [
    "Clio",
    "Megane",
    "Captur",
    "Duster",
    "Kwid",
    "Sandero",
    "Koleos",
    "Arkana",
    "Austral",
    "Espace",
    "Twingo",
    "5 E-Tech",
  ],

  Rimac: ["Concept_One", "Nevera"],

  Rivian: ["R1T", "R1S", "R2", "R3"],

  "Rolls-Royce": [
    "Silver Ghost",
    "Phantom I",
    "Phantom II",
    "Phantom III",
    "Phantom IV",
    "Phantom V",
    "Phantom VI",
    "Phantom VII",
    "Phantom VIII",
    "Silver Cloud I",
    "Silver Cloud II",
    "Silver Cloud III",
    "Silver Shadow",
    "Silver Shadow II",
    "Silver Spirit",
    "Silver Spur",
    "Silver Seraph",
    "Camargue",
    "Corniche I",
    "Corniche II",
    "Corniche III",
    "Corniche IV",
    "Corniche S",
    "Corniche V",
    "Turbo R",
    "Ghost",
    "Wraith",
    "Dawn",
    "Cullinan",
    "Spectre",
  ],

  SEAT: ["Ibiza", "León", "Arona", "Ateca", "Tarraco", "Toledo"],

  Škoda: ["Fabia", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq"],

  Smart: ["Fortwo", "Forfour", "#1", "#3"],

  SSC: ["Ultimate Aero", "Tuatara"],

  Subaru: [
    "Impreza",
    "WRX",
    "BRZ",
    "Legacy",
    "Outback",
    "Forester",
    "Crosstrek",
    "XV",
    "Ascent",
    "Solterra",
  ],

  Suzuki: [
    "Swift",
    "Jimny",
    "Vitara",
    "Grand Vitara",
    "Baleno",
    "Ignis",
    "S-Cross",
  ],

  Tesla: ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],

  Toyota: [
    "Corolla",
    "Camry",
    "Prius",
    "Yaris",
    "Crown",
    "Century",
    "GR86",
    "RAV4",
    "Highlander",
    "4Runner",
    "Sequoia",
    "Fortuner",
    "Corolla Cross",
    "Sienna",
    "Land Cruiser",
    "Hilux",
    "Tacoma",
    "Tundra",
    "Prado",
    "Supra",
    "GR Yaris",
    "GR Corolla",
  ],

  Volkswagen: [
    "Golf",
    "Golf GTI",
    "Golf R",
    "Jetta",
    "Vento",
    "Passat",
    "Polo",
    "Arteon",
    "Beetle",
    "Tiguan",
    "Touareg",
    "Taos",
    "T-Cross",
    "Nivus",
    "Taigo",
    "Atlas",
    "Teramont",
    "ID.3",
    "ID.4",
    "ID. Buzz",
    "Amarok",
    "Saveiro",
  ],

  Volvo: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90", "EX30", "EX90"],

  "W Motors": ["Lykan HyperSport", "Fenyr SuperSport"],

  Xpeng: ["P7", "G9", "G6", "X9"],

  Zeekr: ["001", "007", "009", "X"],
}

export const VEHICLE_COLORS = [
  "Blanco",
  "Negro",
  "Gris",
  "Plata",
  "Rojo",
  "Azul",
  "Azul marino",
  "Verde",
  "Amarillo",
  "Naranja",
  "Marrón",
  "Beige",
  "Dorado",
  "Vinotinto",
] as const

export type VehicleColor = (typeof VEHICLE_COLORS)[number]

export const VEHICLE_TRANSMISSIONS = ["Automático", "Manual"] as const
export type VehicleTransmission = (typeof VEHICLE_TRANSMISSIONS)[number]

export const VEHICLE_FUEL_TYPES = [
  "Gasolina",
  "Diésel",
  "Híbrido",
  "Eléctrico",
] as const
export type VehicleFuelType = (typeof VEHICLE_FUEL_TYPES)[number]

export const VEHICLE_CATEGORIES = [
  "Sedán",
  "SUV",
  "Pickup",
  "Hatchback",
  "Coupé",
  "Van",
  "Deportivo",
  "Camioneta",
] as const
export type VehicleCategory = (typeof VEHICLE_CATEGORIES)[number]

export function getModelsForBrand(brand: string): readonly string[] {
  if ((VEHICLE_BRANDS as readonly string[]).includes(brand)) {
    return MODELS_BY_BRAND[brand as VehicleBrand]
  }
  return []
}